services:
  - type: web
    name: wtfisai
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: wtfisai_db
          property: connectionString

databases:
  - name: wtfisai_db
    ipAllowList: [] 